- id: bgpvpn_configure
  version: 2.0.0
  role: ['primary-controller', 'controller']
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/install-bgpvpn.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1400

- id: horizon_integration
  version: 2.0.0
  role: ['primary-controller', 'controller']
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/horizon_integration.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1400
